### ISSUE TITLE
https://luludansmarue.github.io/kubernetes-docker-lab/docker/intro.html

### ISSUE THREAD

**Issue by Alexkandar** [LuluDansMaRue/kubernetes-docker-lab#11]
> Docker is a container-based virtualization software that allows users to easily create a development environment without installing any virtualization software (e.g. VirtualBox).

I have to use a virtualization software to avoid using any virtualization software ? This phrasing sounds fishy, as if you were trying to sell me this solution over other equivalent solutions.

> Docker architecture is centralized on the daemon, which is used by all of Docker’s components.

"The" daemon ? Please be more specific, maybe explain what a daemon is in one phrase, and describe what dockerd does.
We can also include a link to its documentation :
https://docs.docker.com/engine/reference/commandline/dockerd/

> Data volumes: they are used to persist the data of your containers

Are these filesystem mounted volumes ? When I read "data", I think of a database :thinking: .
Are they shared across all containers ?

**Comment by MarcInthaamnouay** [comment]
Hello @Alexkandar Regarding the first sentence, what I ment was that Docker is virtualization software that provide the ```virtualization``` out of the box without installing any other virtualization driver such as VirtualBox (unless you are using windows)

Secondly ok yes I'll try to add a sentence which explained what a daemon is. 

Regarding the data volumes, yes this is based on the filesystem of your OS. therefore no database is been introduced.  Usually per container. Maybe a link to the doc could be better

**Comment by MarcInthaamnouay** [comment]
Ref in this pr: https://github.com/LuluDansMaRue/kubernetes-docker-lab/pull/16

**Comment by MarcInthaamnouay** [comment]
Resolve in pr 16
