### ISSUE TITLE
https://luludansmarue.github.io/kubernetes-docker-lab/k8s/swarm.html

### ISSUE THREAD

**Issue by Alexkandar** [LuluDansMaRue/kubernetes-docker-lab#13]
> However Docker swarm is not used widely which mean that the community isn’t strong

Got any statistics on Docker swarm and Kubernetes usage ? How can we measure an online community size and interactivity ?

**Comment by MarcInthaamnouay** [comment]
Will add some link regarding this issue but yeah it's mainly based on opinion of devops so far

**Comment by MarcInthaamnouay** [comment]
See: https://github.com/LuluDansMaRue/kubernetes-docker-lab/pull/17
