### ISSUE TITLE
Add anchors to articles titles

### ISSUE THREAD

**Issue by Alexkandar** [LuluDansMaRue/kubernetes-docker-lab#14]
Readers should be able to reference a specific section of the articles.
A simple way of doing this is to add anchors to the titles.

We can :

- Make the titles clickable,
- Add paragraph signs at the end of the titles (see [Symfony documentation](https://symfony.com/doc/current/page_creation.html#creating-a-page-route-and-controller) for example
- Make the icons clickable (but we'll have to put them after every titles, as some are missing currently)

Please let me know what is your favourite choice.

**Comment by MarcInthaamnouay** [comment]
@Alexkandar hmm I think that the Clickable titles should be fine.

**Comment by MarcInthaamnouay** [comment]
fix on 861f230
