### ISSUE TITLE
Add user navigation

### ISSUE THREAD

**Issue by Alexkandar** [LuluDansMaRue/kubernetes-docker-lab#25]
There should be a way for readers to browse from one article to another (appart from occasional hyperlinks in the content).
Maybe a menu or some kind of pagination at the bottom of the articles ?

**Comment by MarcInthaamnouay** [comment]
That could be a good idea however we're limited by the github template.
Therefore this mean that we should copy & paste the menu everywhere...

**Comment by MarcInthaamnouay** [comment]
fix on 861f230
